// ES6 DEFAULT PARAMETER WE CAN DECLARE DEFAULT PARAMETER IN 


/* const getDice = (NUMBER = 6) => {
  return Math.floor(Math.random() * NUMBER) + 1
}

getDice() */
//  WE SHOULD HAVE TO GIVE ARUMENT TO GET RANDOM DICE IF WE DONT GIVE ANY ARGUMENT WE GET (NAN) WE CAN USE DEFAULT PARAMETER  NUMBER = 6  IF WE DON'T GIVE ANY ARGUMENT WE GET 6 DEFAULT ARGUMENTS


